apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo
data:
  config.yaml: |
    log:
      level: info
      job_level: info

    runner:
      file: /data/.runner
      capacity: 2
      timeout: 3h
      shutdown_timeout: 30s
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
      report_interval: 1s
      labels:
        - "ubuntu-latest:docker://node:20-bookworm"
        - "ubuntu-22.04:docker://node:20-bookworm"
        - "alpine:docker://alpine:latest"
        - "docker:docker://node:20-bookworm"

    cache:
      enabled: true
      dir: "/data/cache"

    container:
      network: ""
      privileged: false
      docker_host: "tcp://127.0.0.1:2375"
      workdir_parent: /workspace
      valid_volumes:
        - "**"
