apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
type: Opaque
stringData:
  token: 1CSfnzWsjXrubV3rkFKTxS8p7RUY7Kqc18q05KLO
  instance-url: http://forgejo.forgejo.svc:3000
