apiVersion: v1
kind: Secret
metadata:
  name: authentik-db-credentials
  namespace: authentik
type: kubernetes.io/basic-auth
stringData:
  username: authentik
  password: AuthentikPostgres2026!
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "cloudsea-authentik-super-secret-key-2026-production-minikube"
  AUTHENTIK_BOOTSTRAP_PASSWORD: "AdminAuthentik2026!"
  AUTHENTIK_BOOTSTRAP_TOKEN: "authentik-bootstrap-token-2026-cloudsea-supersecret"
  AUTHENTIK_BOOTSTRAP_EMAIL: "admin@cloudsea.local"
  AUTHENTIK_POSTGRESQL__HOST: "authentik-postgres-rw"
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
  AUTHENTIK_POSTGRESQL__USER: "authentik"
  AUTHENTIK_POSTGRESQL__PASSWORD: "AuthentikPostgres2026!"
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_INSECURE: "true"
  AUTHENTIK_BLUEPRINTS_DIR: "/blueprints"
  AUTHENTIK_LISTEN__METRICS: "0.0.0.0:9300"
