apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/goauthentik/server:2026.8.1
          args:
            - worker
          envFrom:
            - secretRef:
                name: authentik-secrets
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1536Mi
      volumes:
        - name: blueprints
          configMap:
            name: authentik-blueprints
