apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-tls
  namespace: forgejo
spec:
  secretName: forgejo-tls
  issuerRef:
    name: cloudsea-local-ca
    kind: ClusterIssuer
  dnsNames:
    - forgejo.192.168.39.201.nip.io
    - forgejo.192.168.39.200.nip.io
    - forgejo.cloudsea.local
