apiVersion: v1
kind: Secret
metadata:
  name: forgejo-admin-secret
  namespace: forgejo
type: Opaque
stringData:
  username: forgejoadmin
  password: AdminForgejo2026!
  email: admin@cloudsea.local
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
  namespace: forgejo
type: Opaque
stringData:
  secret-key: c3VwZXJzZWNyZXRmb3JnZWpva2V5MjAyNmNsb3Vkc2Vh
