apiVersion: v1
kind: Secret
metadata:
  name: cloudsea-root-ca
  namespace: harbor
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFEjCCAvqgAwIBAgIUURnAJZblpvTVvjm+9R1f9w9r4fAwDQYJKoZIhvcNAQEN
    BQAwITEfMB0GA1UEAxMWQ2xvdWRTZWEgTG9jYWwgUm9vdCBDQTAeFw0yNjA5MDUx
    MjUzMjdaFw0yNjEyMDQxMjUzMjdaMCExHzAdBgNVBAMTFkNsb3VkU2VhIExvY2Fs
    IFJvb3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDXcX88x1z0
    ejCv0jzwNQ7ZavbGl1An9D892MW5urV/TQisLgk9cp4+dE5WDd7ITAkiozXmT9GK
    qUygub+THZNSgW19a95QNSIOr1Y7vxBVqOl85wpXVYdvMkv3QxHyDO520G6mdL9s
    3Bf9tHLqMrsTJeSLSPshThZ8XQWLwZSoInqS9AcoB8fosH9hj8W4LmaqQkBpFlyV
    SwOjmErN+HNMU51fZ5RAFVJ5bk4A7y7p8zikU3QVy2sFansikbbCzhKX+agcWao9
    gKgeyUrXEaREWRRbxUDv541W3hBSWVHnxee0SCDu82o+pdxw2ZiTcltgoIF8YgMM
    Db8Hfsz4u+yHY/+oK+ZG7amgS5GlgLMs+roOpUt2y9qaDlSbD/xB2pTQHTskoHR2
    DanladjKWUwP/jdBiCy3SxlfPS9KlDp2syXcQqI0aIvim5yijnYROZiqD7nBdPUo
    GhW/eQjNhSdL2v/60b5QgJd04sRLDv+oBQqEQYLLzAhtnEubP4O5XRnoO0/xjzW/
    RumLff8k582Db2+uZ55KyjSYSZKy8P+wU+tdU2JJuPpCMZC/V1d+vqUSL5izL8Xo
    SNVgSLWgh77ROWCPA3bFpATK0B6PaOZn/zispeTFx5Id2KWJbnQ6Xe02Fg6z1OMd
    Heq+eoHaV0XdvEgQiszERN5mBl7aL4T+AQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMC
    AqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUIaGE5hoNqVph99A8xIVfFUGW
    rMQwDQYJKoZIhvcNAQENBQADggIBAHFUJkzJB63jb+fdjTHWH5L3vVwKnFlHUHcS
    Wu+ONdw3nQtns49RoWpFvWE7Vtg5JUJbGGzWCuYPJUVJ95y6iPXO+wjxRK3uD4bg
    XlFjFt/DAmtwhxGVzzzD2iJEC32Ph63qBe79yC+Ldx0K+JwSd7KUQT0rkvLCxGK3
    il1Va39aUgQQbvUH0AC3q7Kk57L1SUMpXcwCN7Ud0u0KnsOgA4qkuJ2BC5P2HA6h
    BjgQwi/GtVR7iCJ3jOsrUlfTI68czLTm7lH6YsIgiU899I9vocosjAh3zdyRzB0x
    /MfDhKPeS/t4mvhjnLDPNMu5iJQR5NP2miwVhFGx8tw8i1Ku6acTqHi2SnZHTEga
    YgFdQ3Comx3KkPWh8e6EfQTTGLVWako9IIX07g5u51NMOaxY1krLoGfM4fr5rtaw
    oaneVF7A4puDNJ4jHBhcMfYwUxrRVKbfwMsBRvmVuZiIAOodziAxeANhJdAcJkca
    bn6bdU0auJ7Opna7E2EdD1amfYk0v265VEfzZ+nUwC2jTw3hVCZPUHPklVcCbqLb
    AWZ61fBe8VLiTT5xvIggJlXSykR1SnmrJPnS6fTJtOwvAo8bge1E+RGc/FYOx0Ma
    t0J+LVdKpvecMt1zC4KD+vgoKhxJIPWfEh/xYo+EO/z0yGRQqSfRti9/kxyFJddb
    D0HBQ679
    -----END CERTIFICATE-----
