apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-s3
  namespace: garage
spec:
  parentRefs:
    - name: argocd
      namespace: argocd
  hostnames:
    - "s3.192.168.39.200.nip.io"
    - "*.s3.192.168.39.200.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: garage
          port: 3900
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-ui
  namespace: garage
spec:
  parentRefs:
    - name: argocd
      namespace: argocd
  hostnames:
    - "garage.192.168.39.200.nip.io"
    - "garage-ui.192.168.39.200.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: garage-ui
          port: 8080
