apiVersion: v1
kind: Secret
metadata:
  name: garage-s3-default-key
  namespace: garage
type: Opaque
stringData:
  access-key-id: "GK5dd415c67d451d298f20f069"
  secret-access-key: "43fd1ad1110e02b5043d12c1a669a0a75a9160c6f11633e40ffa0c3c1cb2981d"
  s3-endpoint: "https://s3.192.168.39.200.nip.io"
  s3-endpoint-internal: "http://garage.garage.svc:3900"
  region: "garage"
  bucket: "backups"
