apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - ca-configmap.yaml
  - prometheus.yaml
  - loki.yaml
  - tempo.yaml
  - otel-collector.yaml
  - dashboards.yaml
  - grafana.yaml
  - gateway.yaml
