apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: cloudsea-local-ca
    kind: ClusterIssuer
  dnsNames:
    - "*.192.168.39.200.nip.io"
    - "argocd.192.168.39.200.nip.io"
    - "forgejo.192.168.39.200.nip.io"
    - "garage.192.168.39.200.nip.io"
    - "garage-ui.192.168.39.200.nip.io"
    - "s3.192.168.39.200.nip.io"
    - "*.s3.192.168.39.200.nip.io"
    - "*.cloudsea.local"