global:
  domain: argocd.192.168.39.200.nip.io

configs:
  params:
    server.insecure: "true"
  cm:
    url: https://argocd.192.168.39.200.nip.io
    oidc.config: |
      name: Authentik
      issuer: https://authentik.192.168.39.200.nip.io/application/o/argocd/
      clientID: argocd
      clientSecret: $oidc.authentik.clientSecret
      requestedScopes: ["openid", "profile", "email"]
      rootCA: |
        -----BEGIN CERTIFICATE-----
        MIIFEjCCAvqgAwIBAgIUeM20P0aMBIHqc+dCR/fLqWgA0eIwDQYJKoZIhvcNAQEN
        BQAwITEfMB0GA1UEAxMWQ2xvdWRTZWEgTG9jYWwgUm9vdCBDQTAeFw0yNjEwMDIx
        ODIzNDdaFw0yNjEyMzExODIzNDdaMCExHzAdBgNVBAMTFkNsb3VkU2VhIExvY2Fs
        IFJvb3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCgBzctge3d
        hPLpYP7mDg++rdvbCIgXxf01H0itDrXXQtHH5Rwej3/9GNzpOMnUNxZn068Y6cUv
        0Yh2pFbq/NFFyGpPK9NJ1BZ3sbW0RQO5GuYD/6Cvun1c7TBUjVaN7/KAHC0mZ69v
        Dk3yyZZ8WWEMOyKU9MT3HjvH8gugD/1gi5P5DKcdCMzOnUJoM9mqpUN81k6OA0qv
        rdZ1olr6m3Gew3UtcCh0uVbmzBHdTjKO0aS/bLIbsOtSsn/u/cv6h+hiWahx9c9c
        peeH0mplQcJ2tZjI7yJUILOibaYyMTPmwq+sfApYpDgvFcWomTagng+Ae4gG4wlk
        gues9k37/QFDTJJ1cPXPCA0uox26q29AkxL0L7uUsLrqvUSQkwk8u7iJ6PwVUWyz
        bi8yvGmmSm2kWfDAvSdayEgRma2XyAUt7k5V2yOZP5gxMOPe+80QB61KAiZDeG7N
        1vf7ONq6bfQiG2CUw5qAjKubU7zs77U0WMy5tL6zz8yrGVXeQwfqXeNDpq6ekWzk
        UQCNCpLx+INOPR25SSJOEgFcJGhHI6CqXvd8971nw2B3woC6iQ9M3TROkdnLH1Nz
        q37jYxlWYyuI+9MPpk4oULCH9U1vhWknZEKW4X0JWtrBWZw2dYndcw5rPwqANvfC
        trmmbUz/bSR6szQQBkFoJz4aqoDUx2HgrwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMC
        AqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUGD06T4ybFsE5olq0+gs96lkC
        17gwDQYJKoZIhvcNAQENBQADggIBAD9OAIqclCcVpw4qUc73A1J/2z+ql0TYvbxK
        mDJnMDiw46OwLVFv7NjTI5SukAazQcGX31vUEOeOe0E+tEZXVYOUUuuwZrURNdV8
        ScOdTed51QOVcn+jCp1FZ//5mCiRgRw4EF4Ocq/TGrDXb0HvE0haQ7xq6+cWZedw
        oOn27P3yYGnS49XwlAsebq8SkrM5aOuEv/nULXJtHWbpN9ZhvJB11R0Wy/Dt6wo2
        LoVPiZ6ddC8iH8Q+5tn9FX7Wlc8o+9HI43nuexFwqHd+BWD6p9aqQXAW2bjJ6oNx
        aThmoKmIgHQ0no7pUiDTSFB+rUYLBffKLvwWes4vtiEyJbNkSO7JNGMU1qZn8stM
        EffsqSy5Wk9TZz60qBG/ryrYq1imFbH4LAjwuOKaDP0miy3P20tQNdDM6WtQt83Y
        rH7XMMOetqPafw12VHcMxw+orFoWcouwEXqNZQWkkx/T0q2P2RHfHgOUAFfseeJa
        FA6FoteLEhys8X+cx1x0xP2N2AnfjmJGlccBsUqyHoJp39uIKv9TSvtsZpoKVqdt
        oRZWfnlrDFwhyKSGVy5NmeqdJt/oZs1C5TlP2Ybil36dknxKPDgfIVCccy9sBSDE
        mVYT+4ii3s9xa9cCeljZKAWTXtAkBNNZMMFFktIpFh5c+prG8LjRhQJxsc+kk5Ji
        33jVuEbD
        -----END CERTIFICATE-----
  rbac:
    policy.default: role:admin
    policy.csv: |
      g, authentik Admins, role:admin
      g, akadmin, role:admin
  secret:
    extra:
      oidc.authentik.clientSecret: argocd-authentik-secret-2026

server:
  replicas: 1
  metrics:
    enabled: true

  httproute:
    enabled: false

  ingress:
    enabled: false

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

dex:
  metrics:
    enabled: true
