apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://forgejo.forgejo.svc:3000/forgejoadmin/minikube-fullstack.git
    targetRevision: main
    path: k8s/apps/harbor
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
